const fs = require('fs');
let content = fs.readFileSync('logo/index.html', 'utf-8');

const replacements = [
    ['<span class="eyebrow" style="text-align: center; display: block; margin-bottom: 80px; letter-spacing: 0.05em; color: #555; font-family: Georgia, serif;">2018-2026 || From Middle School to College!</span>', '<span class="eyebrow" style="text-align: center; display: block; margin-bottom: 80px; letter-spacing: 0.05em; color: #555; font-family: Georgia, serif;" data-en="2018-2026 || From Middle School to College!" data-tr="2018-2026 || Ortaokuldan Üniversiteye!">2018-2026 || From Middle School to College!</span>'],
    ['<span class="eyebrow" style="text-align: center; display: block; text-transform: none; letter-spacing: 0; font-weight: normal; margin-bottom: 10px; color: #333; font-family: Georgia, serif;">Thanks for clicking my logo!</span>', '<span class="eyebrow" style="text-align: center; display: block; text-transform: none; letter-spacing: 0; font-weight: normal; margin-bottom: 10px; color: #333; font-family: Georgia, serif;" data-en="Thanks for clicking my logo!" data-tr="Logoma tıkladığınız için teşekkürler!">Thanks for clicking my logo!</span>'],
    ['<h1 style="text-align: center; margin-top: 0;">How to design this logo<span style="font-family: Georgia, serif; background: linear-gradient(to bottom, #171717 75%, #3157d7 75%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">?</span></h1>', '<h1 style="text-align: center; margin-top: 0;" data-en=\'How to design this logo<span style="font-family: Georgia, serif; background: linear-gradient(to bottom, #171717 75%, #3157d7 75%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">?</span>\' data-tr=\'Bu logo nasıl tasarlandı<span style="font-family: Georgia, serif; background: linear-gradient(to bottom, #171717 75%, #3157d7 75%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">?</span>\'>How to design this logo<span style="font-family: Georgia, serif; background: linear-gradient(to bottom, #171717 75%, #3157d7 75%); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">?</span></h1>'],
    ['<p>I started designing my logo when I was in middle school, back in 2018!<br>', '<p data-en="I started designing my logo when I was in middle school, back in 2018!<br>\n                    One day, I just thought, “Why not have a logo for myself?”<br>\n                    I didn\'t really know where I was going to use it, but it turns out I\'m using it today!<br>\n                    So here\'s the story of how I designed my logo. ♡" data-tr="Logomu tasarlamaya 2018\'de, henüz ortaokuldayken başladım!<br>Bir gün sadece \'Neden kendime ait bir logom olmasın?\' diye düşündüm.<br>Nerede kullanacağımı gerçekten bilmiyordum ama görünüşe göre bugün kullanıyorum!<br>İşte logomu nasıl tasarladığımın hikayesi. ♡">I started designing my logo when I was in middle school, back in 2018!<br>'],
    ['<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;">1- Inspiration</h2>', '<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;" data-en="1- Inspiration" data-tr="1- İlham">1- Inspiration</h2>'],
    ['<p>A simple explanation here: First letters of my name (e)lifsu (g)enç and the shape heart ♡ !<br>', '<p data-en="A simple explanation here: First letters of my name (e)lifsu (g)enç and the shape heart ♡ !<br>\n                    I tried to combine these two concepts." data-tr="Burada basit bir açıklama: İsmimin baş harfleri (e)lifsu (g)enç ve kalp şekli ♡ !<br>Bu iki kavramı birleştirmeye çalıştım.">A simple explanation here: First letters of my name (e)lifsu (g)enç and the shape heart ♡ !<br>'],
    ['<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;">2- The Letter E</h2>', '<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;" data-en="2- The Letter E" data-tr="2- E Harfi">2- The Letter E</h2>'],
    ['<p>Since I wanted to use a heart shape, the e letter seemed to fit well on the left half of the heart.<br>', '<p data-en="Since I wanted to use a heart shape, the e letter seemed to fit well on the left half of the heart.<br>\n                    As it can be seen from the sketch below, I tried to rotate it a bit." data-tr="Kalp şeklini kullanmak istediğim için e harfi kalbin sol yarısına oldukça uyumlu görünüyordu.<br>Aşağıdaki çizimden de görülebileceği gibi, onu biraz döndürmeyi denedim.">Since I wanted to use a heart shape, the e letter seemed to fit well on the left half of the heart.<br>'],
    ['<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;">3- The Letter G</h2>', '<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;" data-en="3- The Letter G" data-tr="3- G Harfi">3- The Letter G</h2>'],
    ['<p>The right half of the heart was going to be the g letter. However, I didn\'t want them to look exactly the same,<br>', '<p data-en="The right half of the heart was going to be the g letter. However, I didn\'t want them to look exactly the same,<br>\n                    like a mirror image.<br>\n                    I wanted to make it slightly different but still form a heart shape." data-tr="Kalbin sağ yarısı g harfi olacaktı. Ancak ayna görüntüsü gibi tıpatıp aynı görünmelerini istemedim.<br>Biraz farklı olmasını ama yine de kalp şeklini oluşturmasını istedim.">The right half of the heart was going to be the g letter. However, I didn\'t want them to look exactly the same,<br>'],
    ['<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;">4- Adjustments</h2>', '<h2 style="font-size: clamp(2rem, 3.5vw, 2.8rem); margin-bottom: 45px; letter-spacing: -0.02em;" data-en="4- Adjustments" data-tr="4- Ayarlamalar">4- Adjustments</h2>'],
    ['<p>And I put them together! After several adjustments and some geometric corrections in Illustrator,<br>', '<p data-en="And I put them together! After several adjustments and some geometric corrections in Illustrator,<br>\n                    I finally got the final result!" data-tr="Ve onları birleştirdim! Illustrator\'daki birkaç ayarlama ve bazı geometrik düzeltmelerden sonra,<br>sonunda nihai sonuca ulaştım!">And I put them together! After several adjustments and some geometric corrections in Illustrator,<br>'],
];

for (const [search, replace] of replacements) {
    if (content.includes(search)) {
        content = content.replace(search, replace);
    }
}
fs.writeFileSync('logo/index.html', content, 'utf-8');
console.log('Updated logo/index.html');
