const fs = require('fs');

let content = fs.readFileSync('archive/index.html', 'utf-8');

const replacements = [
    ['<p>This website remembers you!</p><span>This website is actually another project!</span>', '<p data-en="This website remembers you!" data-tr="Bu web sitesi sizi hatırlıyor!">This website remembers you!</p><span data-en="This website is actually another project!" data-tr="Bu web sitesi aslında başka bir proje!">This website is actually another project!</span>'],
    ['<h1>How to code this Website? <button id="btn-see-traces-top"', '<h1><span data-en="How to code this Website?" data-tr="Bu Web Sitesi nasıl kodlanır?">How to code this Website?</span> <button id="btn-see-traces-top" data-en="See traces" data-tr="İzleri gör"'],
    ['>See traces</button></h1>', '>See traces</button></h1>'], // handled above
    ['<h2><span>01</span>The Idea</h2>', '<h2><span>01</span><span data-en="The Idea" data-tr="Fikir">The Idea</span></h2>'],
    ['<p>Websites are usually designed to be looked at. You enter, scroll, click, and leave.</p>', '<p data-en="Websites are usually designed to be looked at. You enter, scroll, click, and leave." data-tr="Web siteleri genellikle bakılmak için tasarlanmıştır. Girer, kaydırır, tıklar ve ayrılırsınız.">Websites are usually designed to be looked at. You enter, scroll, click, and leave.</p>'],
    ['<p><strong><em>But what if visiting a website could leave something behind?</em></strong></p>', '<p data-en="<strong><em>But what if visiting a website could leave something behind?</em></strong>" data-tr="<strong><em>Peki ya bir web sitesini ziyaret etmek geride bir şeyler bırakabilseydi?</em></strong>"><strong><em>But what if visiting a website could leave something behind?</em></strong></p>'],
    ['<p>This project treats interaction as material. Every movement, click, pause, and decision becomes', '<p data-en="This project treats interaction as material. Every movement, click, pause, and decision becomes\n                        part of a temporary digital trace: a record of how someone moved through the website." data-tr="Bu proje etkileşimi materyal olarak ele alır. Her hareket, tıklama, duraklama ve karar geçici bir dijital izin parçası haline gelir: birinin web sitesinde nasıl hareket ettiğinin bir kaydı.">This project treats interaction as material. Every movement, click, pause, and decision becomes'],
    ['part of a temporary digital trace: a record of how someone moved through the website.</p>', 'part of a temporary digital trace: a record of how someone moved through the website.</p>'],
    ['<p>The website observes each session as something unique. These traces are collected, translated and', '<p data-en="The website observes each session as something unique. These traces are collected, translated and\n                        eventually turned into an <strong><em>artifact.</em></strong>" data-tr="Web sitesi her oturumu benzersiz bir şey olarak gözlemler. Bu izler toplanır, çevrilir ve sonunda bir <strong><em>esere</em></strong> dönüştürülür.">The website observes each session as something unique. These traces are collected, translated and'],
    ['eventually turned into an <strong><em>artifact.</em></strong></p>', 'eventually turned into an <strong><em>artifact.</em></strong></p>'],
    ['<p>The visitor is no longer only viewing the website.</p>', '<p data-en="The visitor is no longer only viewing the website." data-tr="Ziyaretçi artık sadece web sitesini görüntülemiyor.">The visitor is no longer only viewing the website.</p>'],
    ['<p>They are contributing to its archive. And that is what makes every trace', '<p data-en="They are contributing to its archive. And that is what makes every trace\n                        valuable.<br /><strong><u>You make the archive different simply by being\n                                yourself.</u></strong><br />No one moves, pauses, clicks, or explores in exactly the\n                        same way you do. Your presence changes the archive, even if all you do is be yourself." data-tr="Arşivine katkıda bulunuyorlar. Ve her izi değerli kılan da budur.<br /><strong><u>Sadece kendiniz olarak arşivi farklı kılıyorsunuz.</u></strong><br />Hiç kimse sizinle tam olarak aynı şekilde hareket etmez, duraklamaz, tıklamaz veya keşfetmez. Yaptığınız tek şey kendiniz olmak olsa bile, varlığınız arşivi değiştirir.">They are contributing to its archive. And that is what makes every trace'],
    ['<h2><span>02</span>Cool, but how to make it work?</h2>', '<h2><span>02</span><span data-en="Cool, but how to make it work?" data-tr="Harika, ama nasıl çalışacak?">Cool, but how to make it work?</span></h2>'],
    ['<p>The system did not appear fully formed. It was built through a series of experiments, failed', '<p data-en="The system did not appear fully formed. It was built through a series of experiments, failed\n                        attempts, small discoveries and many revisions." data-tr="Sistem tamamen oluşmuş halde ortaya çıkmadı. Bir dizi deney, başarısız girişim, küçük keşifler ve birçok revizyonla oluşturuldu.">The system did not appear fully formed. It was built through a series of experiments, failed'],
    ['<p>The first challenge was simple: <strong><em>how can a website remember the way someone moves', '<p data-en="The first challenge was simple: <strong><em>how can a website remember the way someone moves\n                                through it?</em></strong>" data-tr="İlk zorluk basitti: <strong><em>bir web sitesi birinin kendi içinde nasıl hareket ettiğini nasıl hatırlayabilir?</em></strong>">The first challenge was simple: <strong><em>how can a website remember the way someone moves'],
    ['<h2><span>02a</span>Capturing The Movement</h2>', '<h2><span>02a</span><span data-en="Capturing The Movement" data-tr="Hareketi Yakalamak">Capturing The Movement</span></h2>'],
    ['<h3>THE GOAL</h3>', '<h3 data-en="THE GOAL" data-tr="HEDEF">THE GOAL</h3>'],
    ['<p>The first step was to understand how a visitor moves through the website. The mouse normally', '<p data-en="The first step was to understand how a visitor moves through the website. The mouse normally\n                        disappears without leaving any evidence behind. I wanted to turn that temporary movement into\n                        something the website could remember." data-tr="İlk adım, bir ziyaretçinin web sitesinde nasıl hareket ettiğini anlamaktı. Fare normalde arkasında hiçbir iz bırakmadan kaybolur. Bu geçici hareketi web sitesinin hatırlayabileceği bir şeye dönüştürmek istedim.">The first step was to understand how a visitor moves through the website. The mouse normally'],
    ['<p>SUCCESS 01 — movement could become data.</p>', '<p data-en="SUCCESS 01 — movement could become data." data-tr="BAŞARI 01 — hareket veriye dönüşebilir.">SUCCESS 01 — movement could become data.</p>'],
    ['<h2><span>02b</span>But Whose Data Is This?</h2>', '<h2><span>02b</span><span data-en="But Whose Data Is This?" data-tr="Peki Bu Veri Kimin?">But Whose Data Is This?</span></h2>'],
    ['<h3>THE PROBLEM</h3>', '<h3 data-en="THE PROBLEM" data-tr="SORUN">THE PROBLEM</h3>'],
    ['<p>Recording coordinates was not enough. If ten people visited the website, I needed to know which', '<p data-en="Recording coordinates was not enough. If ten people visited the website, I needed to know which\n                        coordinates belonged to which visit." data-tr="Koordinatları kaydetmek yeterli değildi. Web sitesini on kişi ziyaret ederse, hangi koordinatların hangi ziyarete ait olduğunu bilmem gerekiyordu.">Recording coordinates was not enough. If ten people visited the website, I needed to know which'],
    ['<p>The solution was to create a unique session ID for every visit.</p>', '<p data-en="The solution was to create a unique session ID for every visit." data-tr="Çözüm, her ziyaret için benzersiz bir oturum kimliği (session ID) oluşturmaktı.">The solution was to create a unique session ID for every visit.</p>'],
    ['<p>Conceptually, the data now looked', '<p data-en="Conceptually, the data now looked\n                        like:<br /><code>{ sessionId: \'unique-session-id\', points: […] }</code><br />The session ID acts\n                        like a temporary label. I do not need to know who the visitor is. I only need the system to\n                        understand: these points belong to this visit." data-tr="Kavramsal olarak veri artık şöyle görünüyordu:<br /><code>{ sessionId: \'unique-session-id\', points: […] }</code><br />Oturum kimliği geçici bir etiket gibi davranır. Ziyaretçinin kim olduğunu bilmeme gerek yok. Sadece sistemin şunu anlamasına ihtiyacım var: bu noktalar bu ziyarete ait.">Conceptually, the data now looked'],
    ['<p><strong><em>The archive is not about identifying people. It is about distinguishing one', '<p data-en="<strong><em>The archive is not about identifying people. It is about distinguishing one\n                                interaction from another.</em></strong>" data-tr="<strong><em>Arşiv, insanları tanımlamakla ilgili değildir. Bir etkileşimi diğerinden ayırmakla ilgilidir.</em></strong>"><strong><em>The archive is not about identifying people. It is about distinguishing one'],
    ['<p>SUCCESS 02 — each visit could become its own trace.</p>', '<p data-en="SUCCESS 02 — each visit could become its own trace." data-tr="BAŞARI 02 — her ziyaret kendi izine dönüşebilir.">SUCCESS 02 — each visit could become its own trace.</p>'],
    ['<h2><span>02c</span>Sending The Data</h2>', '<h2><span>02c</span><span data-en="Sending The Data" data-tr="Veriyi Göndermek">Sending The Data</span></h2>'],
    ['<p>Mouse movement happens constantly. That means the website can generate many coordinates in a', '<p data-en="Mouse movement happens constantly. That means the website can generate many coordinates in a\n                        short time. Sending every point individually would mean repeatedly communicating with the\n                        backend." data-tr="Fare hareketi sürekli gerçekleşir. Bu, web sitesinin kısa sürede birçok koordinat üretebileceği anlamına gelir. Her noktayı ayrı ayrı göndermek, arka uçla (backend) tekrar tekrar iletişim kurmak anlamına gelirdi.">Mouse movement happens constantly. That means the website can generate many coordinates in a'],
    ['<p>Instead, I grouped points into batches. Rather than sending every point separately, a group of', '<p data-en="Instead, I grouped points into batches. Rather than sending every point separately, a group of\n                        points travels together. Each group has its position in the session." data-tr="Bunun yerine noktaları gruplara ayırdım. Her noktayı ayrı ayrı göndermek yerine, bir grup nokta birlikte hareket eder. Her grubun oturum içindeki konumu bellidir.">Instead, I grouped points into batches. Rather than sending every point separately, a group of'],
    ['<p>SUCCESS 03 — large amounts of movement data could be transferred in manageable pieces.</p>', '<p data-en="SUCCESS 03 — large amounts of movement data could be transferred in manageable pieces." data-tr="BAŞARI 03 — büyük miktarda hareket verisi yönetilebilir parçalar halinde aktarılabilir.">SUCCESS 03 — large amounts of movement data could be transferred in manageable pieces.</p>'],
    ['<h2><span>02d</span>Frontend to Backend</h2>', '<h2><span>02d</span><span data-en="Frontend to Backend" data-tr="Ön Uçtan Arka Uca">Frontend to Backend</span></h2>'],
    ['<p>The browser is responsible for observing the interaction. The collected data then travels to the', '<p data-en="The browser is responsible for observing the interaction. The collected data then travels to the\n                        backend, where each request is checked and organized by visit, points and completion state." data-tr="Tarayıcı etkileşimi gözlemlemekten sorumludur. Toplanan veri daha sonra her isteğin ziyaret, noktalar ve tamamlanma durumuna göre kontrol edildiği ve düzenlendiği arka uca gider.">The browser is responsible for observing the interaction. The collected data then travels to the'],
    ['<p>Each part answers a different question: which visit, what happened, and has the visit ended?</p>', '<p data-en="Each part answers a different question: which visit, what happened, and has the visit ended?" data-tr="Her bölüm farklı bir soruyu yanıtlar: hangi ziyaret, ne oldu ve ziyaret bitti mi?">Each part answers a different question: which visit, what happened, and has the visit ended?</p>'],
    ['<p>SUCCESS 04 — the website could send structured interaction data to its backend.</p>', '<p data-en="SUCCESS 04 — the website could send structured interaction data to its backend." data-tr="BAŞARI 04 — web sitesi yapılandırılmış etkileşim verilerini arka uca gönderebilir.">SUCCESS 04 — the website could send structured interaction data to its backend.</p>'],
    ['<h2><span>02e</span>Knowing When It’s Over</h2>', '<h2><span>02e</span><span data-en="Knowing When It’s Over" data-tr="Ne Zaman Bittiğini Bilmek">Knowing When It’s Over</span></h2>'],
    ['<p><strong><em>One of the more difficult questions was surprisingly simple: when is a visit', '<p data-en="<strong><em>One of the more difficult questions was surprisingly simple: when is a visit\n                                finished?</em></strong>" data-tr="<strong><em>Daha zor sorulardan biri şaşırtıcı derecede basitti: bir ziyaret ne zaman biter?</em></strong>"><strong><em>One of the more difficult questions was surprisingly simple: when is a visit'],
    ['<p>The website could collect information while someone was there, but it also needed to recognize', '<p data-en="The website could collect information while someone was there, but it also needed to recognize\n                        the final part of that visit." data-tr="Web sitesi biri oradayken bilgi toplayabiliyordu, ancak o ziyaretin son kısmını da tanıması gerekiyordu.">The website could collect information while someone was there, but it also needed to recognize'],
    ['<p>At first the final session was not appearing where expected. The interaction worked, but the', '<p data-en="At first the final session was not appearing where expected. The interaction worked, but the\n                        artifact did not appear immediately. A later revision connected the final interaction directly\n                        to the archive." data-tr="Başlangıçta son oturum beklenildiği yerde görünmüyordu. Etkileşim çalışıyordu ama eser hemen ortaya çıkmıyordu. Daha sonraki bir revizyon, son etkileşimi doğrudan arşive bağladı.">At first the final session was not appearing where expected. The interaction worked, but the'],
    ['<h2><span>02f</span>From Data To Artifact!</h2>', '<h2><span>02f</span><span data-en="From Data To Artifact!" data-tr="Veriden Esere!">From Data To Artifact!</span></h2>'],
    ['<p>At this point the system could identify a visit, record its movement, group the data and', '<p data-en="At this point the system could identify a visit, record its movement, group the data and\n                        understand when it had finished." data-tr="Bu noktada sistem bir ziyareti tanımlayabilir, hareketini kaydedebilir, verileri gruplandırabilir ve ne zaman bittiğini anlayabilirdi.">At this point the system could identify a visit, record its movement, group the data and'],
    ['<p>But raw coordinates were never meant to be the final result. <strong><em>The next step was', '<p data-en="But raw coordinates were never meant to be the final result. <strong><em>The next step was\n                                translation.</em></strong>" data-tr="Ancak ham koordinatların hiçbir zaman nihai sonuç olması amaçlanmamıştı. <strong><em>Bir sonraki adım çeviriydi.</em></strong>">But raw coordinates were never meant to be the final result. <strong><em>The next step was'],
    ['<p>The collected session data is passed to the backend, where it is transformed into a PDF.', '<p data-en="The collected session data is passed to the backend, where it is transformed into a PDF.\n                        <strong><em>The PDF becomes a visual record of that particular visit.</em></strong>" data-tr="Toplanan oturum verileri arka uca iletilir ve burada bir PDF\'e dönüştürülür.\n                        <strong><em>PDF, o özel ziyaretin görsel bir kaydı haline gelir.</em></strong>">The collected session data is passed to the backend, where it is transformed into a PDF.'],
    ['<h2><span>02g</span>Building The Archive</h2>', '<h2><span>02g</span><span data-en="Building The Archive" data-tr="Arşivi Oluşturmak">Building The Archive</span></h2>'],
    ['<p>Generating the document was not enough. It also needed somewhere to live. Each completed session', '<p data-en="Generating the document was not enough. It also needed somewhere to live. Each completed session\n                        is connected to its PDF and stored so individual visits become part of a larger collection." data-tr="Belgeyi oluşturmak yeterli değildi. Aynı zamanda yaşayacağı bir yere de ihtiyacı vardı. Tamamlanan her oturum kendi PDF\'ine bağlanır ve saklanır, böylece bireysel ziyaretler daha büyük bir koleksiyonun parçası haline gelir.">Generating the document was not enough. It also needed somewhere to live. Each completed session'],
    ['<p><strong><em>The archive therefore does not contain documents I designed individually. It contains', '<p data-en="<strong><em>The archive therefore does not contain documents I designed individually. It contains\n                                documents generated by the people who visited the website.</em></strong>" data-tr="<strong><em>Bu nedenle arşiv, bireysel olarak tasarladığım belgeleri içermez. Web sitesini ziyaret eden kişiler tarafından oluşturulan belgeleri içerir.</em></strong>"><strong><em>The archive therefore does not contain documents I designed individually. It contains'],
    ['<h1>All traces</h1>', '<h1 data-en="All traces" data-tr="Tüm izler">All traces</h1>'],
    ['<button class="archive-more" id="more-traces" type="button"\n                hidden>See more <span>↓</span></button>', '<button class="archive-more" id="more-traces" type="button" hidden data-en="See more <span>↓</span>" data-tr="Daha fazla gör <span>↓</span>">See more <span>↓</span></button>']
];

for (const [search, replace] of replacements) {
    if (content.includes(search)) {
        content = content.replace(search, replace);
    }
}

fs.writeFileSync('archive/index.html', content, 'utf-8');
console.log('Updated archive/index.html');
