const fs = require('fs');

let content = fs.readFileSync('about/index.html', 'utf8');
const replacements = [
    ['<span class="eyebrow">ABOUT / ELIFSU GENÇ</span>', '<span class="eyebrow" data-en="ABOUT / ELIFSU GENÇ" data-tr="HAKKINDA / ELİFSU GENÇ">ABOUT / ELIFSU GENÇ</span>'],
    ['<h1 id="about-title">About<span class="accent">.</span></h1>', '<h1 id="about-title" data-en="About<span class=\'accent\'>.</span>" data-tr="Hakkında<span class=\'accent\'>.</span>">About<span class="accent">.</span></h1>'],
    ['<p><strong><em>Elifsu Genç</em></strong> is an interior design and architecture student based in\r\n                    Istanbul/Türkiye. But she usually likes to call herself a <em>“critical designer”</em> instead.</p>', '<p data-en="<strong><em>Elifsu Genç</em></strong> is an interior design and architecture student based in Istanbul/Türkiye. But she usually likes to call herself a <em>“critical designer”</em> instead." data-tr="<strong><em>Elifsu Genç</em></strong> İstanbul/Türkiye\'de yaşayan bir iç mimarlık ve mimarlık öğrencisidir. Ancak o kendini genellikle <em>“eleştirel tasarımcı”</em> olarak adlandırmayı tercih eder."><strong><em>Elifsu Genç</em></strong> is an interior design and architecture student based in\r\n                    Istanbul/Türkiye. But she usually likes to call herself a <em>“critical designer”</em> instead.</p>'],
    ['<p>Her work explores the relationships between <strong><em>people, materials, environments, and\r\n                            technology.</em></strong></p>', '<p data-en="Her work explores the relationships between <strong><em>people, materials, environments, and technology.</em></strong>" data-tr="Çalışmaları <strong><em>insanlar, materyaller, çevreler ve teknoloji</em></strong> arasındaki ilişkileri araştırır.">Her work explores the relationships between <strong><em>people, materials, environments, and\r\n                            technology.</em></strong></p>'],
    ['<p>She is interested in how designed systems can respond to human presence, behavior, and interaction,\r\n                    and <strong><em>how materials can become active participants in these relationships.</em></strong>\r\n                </p>', '<p data-en="She is interested in how designed systems can respond to human presence, behavior, and interaction, and <strong><em>how materials can become active participants in these relationships.</em></strong>" data-tr="Tasarlanmış sistemlerin insan varlığına, davranışına ve etkileşimine nasıl yanıt verebileceğiyle ve <strong><em>materyallerin bu ilişkilerde nasıl aktif katılımcılar olabileceğiyle</em></strong> ilgilenmektedir.">She is interested in how designed systems can respond to human presence, behavior, and interaction,\r\n                    and <strong><em>how materials can become active participants in these relationships.</em></strong>\r\n                </p>'],
    ['<p>Her interests lie in experimental and research-driven practices that bring together spatial design,\r\n                    material exploration, and emerging technologies.</p>', '<p data-en="Her interests lie in experimental and research-driven practices that bring together spatial design, material exploration, and emerging technologies." data-tr="İlgi alanları mekan tasarımı, materyal keşfi ve gelişen teknolojileri bir araya getiren deneysel ve araştırma odaklı pratiklerdir.">Her interests lie in experimental and research-driven practices that bring together spatial design,\r\n                    material exploration, and emerging technologies.</p>'],
    ['<p>She is currently developing her practice around interactive environments, material behavior, and\r\n                    human-centered design.</p>', '<p data-en="She is currently developing her practice around interactive environments, material behavior, and human-centered design." data-tr="Şu anda pratiklerini etkileşimli ortamlar, materyal davranışı ve insan merkezli tasarım üzerine geliştirmektedir.">She is currently developing her practice around interactive environments, material behavior, and\r\n                    human-centered design.</p>'],
    ['<p class="about-note"><em>Word are really important for her. She likes to give meaning to every word she\r\n                    uses in her projects. To understand her mind you need to understand her words first.</em></p>', '<p class="about-note" data-en="<em>Word are really important for her. She likes to give meaning to every word she uses in her projects. To understand her mind you need to understand her words first.</em>" data-tr="<em>Kelimeler onun için gerçekten önemlidir. Projelerinde kullandığı her kelimeye anlam yüklemeyi sever. Zihnini anlamak için önce kelimelerini anlamalısınız.</em>"><em>Word are really important for her. She likes to give meaning to every word she\r\n                    uses in her projects. To understand her mind you need to understand her words first.</em></p>']
];

for (const [search, replace] of replacements) {
    if (content.includes(search)) {
        content = content.replace(search, replace);
    } else {
        // Also try with \n instead of \r\n
        const search2 = search.replace(/\r\n/g, '\n');
        if (content.includes(search2)) {
            content = content.replace(search2, replace);
        }
    }
}
fs.writeFileSync('about/index.html', content, 'utf8');
console.log('Updated about/index.html');
